### PR TITLE
Linting fix 

### PR DESCRIPTION
**Pull request by aalchen**
- fix for this error below
- removing a console log 
- fixing the GloballySearched db call, should only be returning 12 so added a `.limit` to the db call 

Screenshot 2023-06-23 at 7 39 59 PM

### CODE REVIEW

**Review by kernelkay — COMMENTED** [review]
@aalchen hmm personally more of a fan of the skeleton for typing/search animations 😅 Fade looks a bit strange when we're animating at each character imo! 

Thoughts? @rrichc  @Parmvir-S  @JeromeTing

**Comment by JeromeTing** [comment]
I also agree, I like the skeleton more. I think it's the abrupt transition from fading to the songs you might like result that seems strange

**Comment by aalchen** [comment]
updated to keep skeleton, just fixing linting errors on rendering/browser side now!

**Comment by JeromeTing** [comment]
there's a conflict :(

**Comment by aalchen** [comment]
conflict resolved! 

+ removing a console log 
+ fixing the GloballySearched db call to only return last 12 values (sorted by recent) 

also noticed another console log thing on the Scoreboard page, but will get to it at another time

**Comment by JeromeTing** [comment]
lgtm

**Pull request merged**
