### PR TITLE
Task: Code Clean Up

### PR DESCRIPTION
**Pull request by Parmvir-S**
### Basic Info:
- The goal of this task was to clean up the code a little bit. This involved scanning the code and removing unnecessary comments and fixing formatting.

### Changes:
- Root Folder
	- Deleted `src` folder in the main project folder. It had subfolders `assets` and `images` which were both empty.
	- Deleted old `server` folder. Just had node modules in it.
	- Deleted default `public` folder as we are not using it.
- Backend
     - Removed the index router from routes and associated import in app.js. I believe this just boilerplate code that `express-generator` provides. 
	- Removed the following line as well: `app.use(express.static(path.join(__dirname, "public")));`
- Frontend
     - Removed comments and formatted the code.
- Flask Server
    -  Just removed TODO comment and print(similar_songs) call

**NOTE:**
- To double check, before merging anything into the main branch it might be a good idea to see if the changes didn't break anything on more than one computer.

### CODE REVIEW

**Comment by rrichc** [comment]
Just to make sure - have you tested to make sure everything works locally?

**Comment by Parmvir-S** [comment]
> Just to make sure - have you tested to make sure everything works locally?

@rrichc Everything seems to work fine for me. However, I wasn't using the flask server when testing. I had changed useCustomMLModel to false when I was running everything

**Review by JeromeTing — APPROVED** [review]
Looks good. I tested it locally and nothing broke on me (including the flask server).

**Review by rrichc — APPROVED** [review]
Also fine for me!

**Pull request merged**
